services:
  nodejs:
    container_name: discord-ruisbot
    build: .
    volumes:
      - ./.env:/usr/src/app.env # create your own .env file using env.example
      - ./firebase-adminsdk-credential.json:/usr/src/app/config/firebase-adminsdk-credential.json # download it from your firebase console
    environment:
      - TZ=Europe/Zurich
    ports:
      - "8083:80"
    restart: always
