services:
  nodejs:
    container_name: discord-ruisbot
    build: .
    image: rpdjf/discord-ruisbot
    volumes:
      - ./.env:/usr/src/app.env # create your own .env file using env.example
      - ./firebase-adminsdk-credential.json:/usr/src/app/config/firebase-adminsdk-credential.json # download it from your firebase console
    environment:
      - TZ=Europe/Zurich
    restart: always
