services:
  nodejs:
    container_name: discord-ruisbot
    build: .
    image: rpdjf/discord-ruisbot
    volumes:
      - ./.env:/usr/src/app.env # create your own .env file using env.example
    environment:
      - TZ=Europe/Zurich
    restart: always
